name: right
description: UI kit for flutter apps
version: 0.0.4
homepage: null

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  superellipse_shape: ^0.2.0

dev_dependencies:

  flutter_test:
    sdk: flutter
